### ISSUE TITLE
Fehlverhalten des Parsers

### ISSUE THREAD

**Issue by dermondbaer** [g4rgoil/graphing_calculator#12]
@g4rgoil 

Ein Ausdruck der Syntax 

`( x + y ) * z`

verursacht einen _IndexError_ im Parser. Ausschlaggebend scheint die öffnende Klammer zu sein.

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python35\lib\tkinter\__init__.py", line 1549, in __call__
    return self.func(*args)
  File "D:\Bibliotheken\Paul\GitHub\graphing_calculator\Gui.py", line 173, in equals
    tmp = self.__parser.make_expression_postfix(self.__parse_str)
  File "D:\Bibliotheken\Paul\GitHub\graphing_calculator\Parser.py", line 49, in make_expression_postfix
    postfix = self.__make_postfix(infix)
  File "D:\Bibliotheken\Paul\GitHub\graphing_calculator\Parser.py", line 106, in __make_postfix
    if operator_stack[-1] in self.__supported_functions:
IndexError: list index out of range
```

**Comment by pmehnert** [comment]
Hast du das mit x, y und z eingegeben?

**Comment by pmehnert** [comment]
Ich habe den Fehler gefunden, mit dem nächsten update wird er behoben.

**Comment by pmehnert** [comment]
Ok, der Bug müsste jetzt gefixt sein.
Y und Z sind aber noch nicht als Variablen hinzugefügt. Das müsstest du mit Zahlenwerten machen.

**Comment by dermondbaer** [comment]
Nope, war nur ein Platzhalter. Y und Z brauchen wir ja auch nicht.

Eine Idee wäre allerdings eine Memofunktion wie die üblichen M+/M-/MC Tasten. Vielleicht halt mit Variablen oder so.

**Comment by pmehnert** [comment]
Ich hab x, y und z jetzt einfach mal in die xml reingepackt.
Das mit den M-Tasten können wir uns später noch mal anschauen.

**Comment by dermondbaer** [comment]
Ok :)

**Comment by pmehnert** [comment]
Ich hab übrigens ein bisschen Doku zum Parser und ParserTree geschrieben.
So könnt das dann am Ende denk ich mal aussehen.

**Comment by dermondbaer** [comment]
Jop alles klar ich denk das mach ich bei mir auch irgendwann.

**Comment by pmehnert** [comment]
Den Thread könnte man dann doch mal schließen, oder?
