### ISSUE TITLE
Notation der Ausdrücke

### ISSUE THREAD

**Issue by dermondbaer** [g4rgoil/graphing_calculator#14]
@g4rgoil 
Wie werden mathematische Funktionen wie _sin, root, log,_ korrekt an den Parser übergeben?
Mit Leerzeichen, also `sin (`, oder ohne, also `sin(`?

Ist außerdem die Notation `.2` in Ordnung? Soll der Rechner nur `0.2` akzeptieren oder auch `.2` und wenn ja, soll ich in _GUI.py_ die Notation ggfs anpassen lassen oder akzeptiert der Parser das?

**Comment by pmehnert** [comment]
Funktionen können als "sin(" übergeben werden.
Mit ".2" kommt er noch nicht klar. Das kann ich aber auch noch hinzufügen. Das muss aber erst mal noch warten.

**Comment by dermondbaer** [comment]
Ok, dann lass ichs offen. Wollte nur wissen, in welchen Aufgabenbereich so was fällt.

**Comment by pmehnert** [comment]
Die Notation in der Form '.5' anstelle '0.5' wird mit der kommenden Version des Parsers unterstützt.
