### ISSUE TITLE
Mathematik Bibliothek

### ISSUE THREAD

**Issue by pmehnert** [g4rgoil/graphing_calculator#17]
Wäre es vielleicht das beste, wenn ich jetzt erstmal ohne unsere eigene Mathe Bibliothek einen Calculator schreibe, weil ohne diese Bibliothek letztendlich nichts funktioniert.

**Comment by dermondbaer** [comment]
Da funktioniert echt nicht.

**Comment by pmehnert** [comment]
Was mir auch aufgefallen ist, die python interne Bibliothek ist in C implementiert. Dementsprechend muss man das alles vielleicht noch mal überdenken.

**Comment by dermondbaer** [comment]
Naja, geht ja nicht unbedingt um Geschwindigkeit, sondern um den Anspruch in der Programmierung ... aber stimmt schon ist natürlich langsamer

**Comment by pmehnert** [comment]
Naja, man kann für den Anfang auf die internen Funktionen zurückgreifen, und sie dann später ersetzen. Je nachdem, wenn Max das machen will.

**Comment by dermondbaer** [comment]
Ja genau, dann haben wir schon mal was :)

**Comment by pmehnert** [comment]
Ok, dann implementiere ich den Calculator mal in den nächsten Tagen.

**Comment by pmehnert** [comment]
@dermondbaer @feaa84eb8ccb9fb609265fceec91729a 
Also die Mathe Bibliothek ist jetzt im master (math_library). Die Datei des Parser wurde zu math_parser umbenannt, genauso die des Calculators.
