### ISSUE TITLE
Noch zu implementierende Funktionen.

### ISSUE THREAD

**Issue by pmehnert** [g4rgoil/graphing_calculator#27]
@dermondbaer @feaa84eb8ccb9fb609265fceec91729a 
Ich hatte mir gedacht, dass wir in diesem Thread, mathematische Funktionen diskutieren könnten, die wir (also Max) noch implementieren müssen.
Aktuell habe ich, abgesehen von den aus python übernommenen Funktionen: binompdf, binomcdf, ncr, npr.
Zusätzlich brauchen wir auf jeden Fall noch: nderiv, fnint
Ganz gut wären auch noch: rootn, modulo ...

**Comment by dermondbaer** [comment]
d.h. das frühere "root" ist jetzt ersetzt durch "rootn"?

**Comment by pmehnert** [comment]
@dermondbaer Nein, root gibt es bisher noch gar nicht, sondern nur sqrt. Wie wir die Funktionen benennen, können wir uns später noch überlegen. 

Edit: btw kannst du Max mal darum bitten, dass er sich hier auch beteiligt?

**Comment by dermondbaer** [comment]
Wie wäre es übrigens, wenn du noch dokumentierst, welche Funktionen mit welchen Parametern übergeben werden können? Ich glaub, ich fand die xml gar nicht so schlecht, weil darin alles direkt zu erkennen war.

**Comment by pmehnert** [comment]
Ich kann das einfach in die math library reinschreiben.
Ich hab sowieso schon ein bissle Dokumentation dafür geschrieben.

**Comment by dermondbaer** [comment]
Ok danke!

**Comment by pmehnert** [comment]
Kein Ding. :smiley: 
Wie  gesagt, wär halt nice, wenn Max den Thread auch mal lesen würde.

**Comment by dermondbaer** [comment]
sag das @feaa84eb8ccb9fb609265fceec91729a ;)

**Comment by pmehnert** [comment]
Der hat GitHub doch auf ner spam mail laufen und ich hab grad echt keine Lust den auf Whatsapp anzuschreiben.

**Comment by dermondbaer** [comment]
Sags ihm morgen ...

**Comment by feaa84eb8ccb9fb609265fceec91729a** [comment]
Ich kümmer mich morgen und am Wochenende drum

**Comment by pmehnert** [comment]
Solange du es machst, ist mir egal wann. :smile:
