### ISSUE TITLE
Rundung der Ergebnisse (Float Fehler)

### ISSUE THREAD

**Issue by pmehnert** [g4rgoil/graphing_calculator#32]
@dermondbaer 
Was hältst du davon, wenn ich die Ergebnisse einfach auf 16 Nachkommastellen runde? Damit hätten wir eigentlich eine ganz gute Genauigkeit.

**Comment by dermondbaer** [comment]
Bei der Ableitung ist der Wert doch schon bei einer viel geringeren Anzahl an Kommastellen ungenau?!

**Comment by pmehnert** [comment]
Ja auf irgend eine Weise müssen wir runden. Wie wolltest du das anders lösen?

**Comment by dermondbaer** [comment]
https://docs.python.org/3.5/library/decimal.html

**Comment by pmehnert** [comment]
@dermondbaer 
Das hört sich doch mal ganz nice an. :D

**Comment by pmehnert** [comment]
@dermondbaer 
Also, ich hab das jetzt mal ansatzweise implementiert. Das einzige Problem ist, dass ich spätestens bei trigonometrischen Funktionen wieder mit Float rechnen muss. Dadurch entstehen dann wieder leichte Rundungsfehler. Ich könnte natürlich Funktionen schreiben, die das mit Decimal machen, dann wäre die Performance halt für den Arsch. :skull:

**Comment by dermondbaer** [comment]
Naja, Performance sollte immer hinter Funktionalität stehen, oder?

**Comment by pmehnert** [comment]
Ok, ich schau dann mal morgen, ob ich da eigene Funktionen für schreiben kann.

Edit: Ich rechne mit 28 Nachkommastellen (Das ist der Standardwert)

**Comment by pmehnert** [comment]
Ähhhmmm, trigonometrische Funktionen zu implementieren ist absoluter Schwachsinn. Daraus könnte man ein komplettes Projekt machen. Die Implementierung ist viel zu komplex!

**Comment by dermondbaer** [comment]
Oke ... dann reden wir noch mal drüber am Freitag oder so.

**Comment by pmehnert** [comment]
http://keisan.casio.com/calculator

**Comment by pmehnert** [comment]
@dermondbaer 
Also, der Rechner arbeitet jetzt mit decimal. Es wird während dem Rechnen nicht gerundet. Wenn man einen ParserTree ausgibt, kann man angeben, wie viele Stellen ausgegeben werden sollen.
