### ISSUE TITLE
Popup zum Einstellen der Größe des Koordinatensystems

### ISSUE THREAD

**Issue by pmehnert** [g4rgoil/graphing_calculator#37]
@dermondbaer 
Also, ich hab mir da nochmal ein paar Gedanken gemacht. Ich wäre dafür, dass man im Einstellungsmenü die Standardgröße (Anzahl der  Einheiten) des Koordinatensystems festlegen kann. Wird das Koordinatensystem dann gezeichnet, wird diese Grundeinstellung verwendet und kein Popup  erscheint.
Will man die Größe dann spontan verändern, klickt man auf einen Button. Dieser ruft die restart() Funktion des Gui auf. In einem Popup kann man dann die gewünschte Größe eingeben.

**Comment by pmehnert** [comment]
@dermondbaer 
Btw: Das Koordinatensystem erstellt jetzt kein neues Fenster mehr, sondern wird in einem master Element erstellt. Der Dialog zum angeben der Größe ist aber noch vorhanden. Das stell ich erst später um.

**Comment by dermondbaer** [comment]
Ok!

**Comment by pmehnert** [comment]
kden
